name: pref
description: Create Preference Screens easily with advanced features and sub-pages
version: 6.0.0
homepage: https://github.com/DavBfr/flutter_pref
author: David PHAM-VAN <dev.nfet.net@gmail.com>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
