name: pref
description: Create Preference Screens easily with advanced features and sub-pages
homepage: https://github.com/DavBfr/flutter_pref/tree/master/pref
repository: https://github.com/DavBfr/flutter_pref
issue_tracker: https://github.com/DavBfr/flutter_pref/issues
author: David PHAM-VAN <dev.nfet.net@gmail.com>
version: 2.0.0-nullsafety

environment:
  sdk: ">=2.12.0-29.10.beta <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety

flutter:
