name: readme_to_dart
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta:
  string_scanner:
  pref:
  markdown:

dependency_overrides:
  pref:
    path: ../pref
